# Generated by Django 5.0.2 on 2024-03-11 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(blank=True, max_length=20)),
                ('courseTitle', models.CharField(max_length=100)),
                ('shortDescription', models.CharField(max_length=300)),
                ('courseProfessors', models.CharField(max_length=300)),
                ('coursePolicies', models.CharField(blank=True, max_length=300)),
                ('nominalCourseDifficultyReview', models.IntegerField()),
                ('courseDemand', models.IntegerField(blank=True)),
                ('passingRate', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseReview', models.CharField(blank=True, max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFailedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPassedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('systemReview', models.CharField(blank=True, max_length=500)),
                ('failedCourses', models.ManyToManyField(to='home.studentfailedcourse')),
                ('passedCourses', models.ManyToManyField(to='home.studentpassedcourse')),
            ],
        ),
    ]
