# Generated by Django 5.0.2 on 2024-02-27 19:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=100)),
                ('shortDescription', models.CharField(max_length=300)),
                ('courseProfessors', models.CharField(max_length=300)),
                ('coursePolicies', models.CharField(blank=True, max_length=300)),
                ('nominalCourseDifficultyReview', models.IntegerField()),
                ('courseReview', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, size=None)),
                ('courseDemand', models.IntegerField()),
                ('passingRate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('passedCourses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('failedCourses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('systemReview', models.CharField(max_length=500)),
            ],
        ),
    ]
