# Generated by Django 5.0.2 on 2024-03-15 04:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=30)),
                ('courseTitle', models.CharField(max_length=100)),
                ('shortDescription', models.CharField(blank=True, max_length=300)),
                ('courseProfessors', models.CharField(blank=True, max_length=300)),
                ('coursePolicies', models.CharField(blank=True, max_length=300)),
                ('nominalCourseDifficultyReview', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('courseDemand', models.IntegerField(blank=True, null=True)),
                ('passingRate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseReview', models.CharField(blank=True, max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFailedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPassedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('systemReview', models.CharField(blank=True, max_length=500)),
                ('failedCourses', models.ManyToManyField(blank=True, to='home.studentfailedcourse')),
                ('passedCourses', models.ManyToManyField(blank=True, to='home.studentpassedcourse')),
            ],
        ),
    ]
