# Generated by Django 5.0.2 on 2024-03-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='failedCourses',
            field=models.ManyToManyField(blank=True, to='home.studentfailedcourse'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passedCourses',
            field=models.ManyToManyField(blank=True, to='home.studentpassedcourse'),
        ),
    ]
