# Generated by Django 5.0.2 on 2024-02-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_course_coursedemand_alter_course_passingrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='systemReview',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
