# Generated by Django 5.0.2 on 2024-03-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_course_shortdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseCoreq',
            field=models.ManyToManyField(blank=True, related_name='CourseCoreq', to='home.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursePrereq',
            field=models.ManyToManyField(blank=True, related_name='CoursePrereq', to='home.course'),
        ),
    ]
