# Generated by Django 5.0.2 on 2024-05-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_student_failedcourses_student_takeablecourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='courseReview',
            field=models.TextField(),
        ),
    ]
